name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/498336110354/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-deployer-sa@taxi-tips-mlops-dev.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag europe-west1-docker.pkg.dev/taxi-tips-mlops-dev/mlops-docker-repo/taxi-tips-api:latest src/proxy/

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy taxi-tips-api-dev \
            --image europe-west1-docker.pkg.dev/taxi-tips-mlops-dev/mlops-docker-repo/taxi-tips-api:latest \
            --region europe-west1 \
            --allow-unauthenticated